# Generated by Django 5.2.1 on 2025-06-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disponible', models.BooleanField(default=True)),
                ('url_image', models.CharField(default='img/no-image.png', max_length=200)),
            ],
        ),
    ]
