# Generated by Django 5.2 on 2025-05-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='tiempo',
            field=models.IntegerField(default=10),
        ),
    ]
