# Generated by Django 5.2.1 on 2025-05-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0003_logger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.TextField(max_length=100)),
                ('nombres', models.TextField(max_length=100)),
            ],
        ),
    ]
